---
title: 异步回调
date: 2022-01-09
categories:
 - 多线程
tags:
 - JUC
sidebar: 'auto'
---
## 14、异步回调

> Future 设计的初衷：对将来的某个事件结果进行建模！

其实就是前端 --> 发送ajax异步请求给后端

![image-20211121132712360](https://gitee.com/yishenlaoban/git-typore/raw/master/images/image-20211121132712360.png) 

但是我们平时都使用**CompletableFuture**

**方法：**

![image-20211121143859448](https://gitee.com/yishenlaoban/git-typore/raw/master/images/image-20211121143859448.png) 

![image-20211121143942551](https://gitee.com/yishenlaoban/git-typore/raw/master/images/image-20211121143942551.png) 

**（1）没有放回值的 runAsync 异步回调**

  ```java
/*
* 异步调用  CompletableFuture
*   1.异步执行
*   2.成功回调
*   3.失败回调*/
public class Demo {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        //没有返回值的 runAsync 异步回调
        CompletableFuture<Void> completableFuture = CompletableFuture.runAsync(()->{
            try {
                TimeUnit.SECONDS.sleep(2);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(Thread.currentThread().getName() + ".....");
        });
        System.out.println("111111"); //其他的任务(这里是主任务)
        /*异步：用的时候就执行，其他时间执行其他的任务*/
        System.out.println(completableFuture.get());//获得执行结果

    }
}
  ```



**（2）有返回值的 supplyAsync异步回调**

 ```java
public class Demo2 {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
         /*有返回值的异步回调*/
        CompletableFuture<Integer> future = CompletableFuture.supplyAsync(() -> {
            System.out.println(Thread.currentThread().getName());
            try {
                TimeUnit.SECONDS.sleep(2);
                int i = 1 / 0;  /*制造一个错误信息*/
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return 1024;
        });

        System.out.println(future.whenComplete((t, u) -> {
            //success 回调
            System.out.println("t=>" + t); //正确的返回结果
            System.out.println("u=>" + u); //抛出异常的错误信息
        }).exceptionally((e) -> {
            //error 回调
            System.out.println(e.getMessage());
            return 404;
        }).get());

    }
}
 ```

**whenComplete**: 有两个参数，一个是t 一个是u

T：是代表的 **正常返回的结果**；

U：是代表的 **抛出异常的错误信息**；

如果发生了异常，get可以获取到**exceptionally**返回的值；